### ISSUE TITLE
OpenAL examples break build in systems with FFMPEG headers installed

### ISSUE THREAD

**Issue by Fordi** [pspdev/psplibraries#33]
Quick fix is to just disable examples (in scripts/openal.sh, add "-D EXAMPLES=OFF" to the psp-cmake line).

**Comment by sharkwouter** [comment]
it's likely this issue can be closed, since a fix for it seems to have been merged.

**Comment by dbeef** [comment]
Thanks @sharkwouter, linked PR is indeed merged. Closing.
