### ISSUE TITLE
make: no rule to make target 'clean'. Stop. (smpeg-psp)

### ISSUE THREAD

**Issue by kosmas12** [pspdev/psplibraries#40]
Hello!

I am trying to install psplibraries on Ubuntu 10.04 (VM of course) and when running the ./libraries-sudo.sh script it clones smpeg-psp successfully from the source I told it to (http://jim.psp.sh/svn/psp/trunk/ smpeg-psp) make reports an error saying:

make: *** No rule to make target `clean'.  Stop.

There are no makefiles on the smpeg-psp directory but there are makefiles in its sub-directories. How can I fix this?

**Comment by carstene1ns** [comment]
Can you explain what you are trying to do?
- Why the old vm?
- Why the (probably wrong) changed location of the smpeg library?
