### ISSUE TITLE
OpenAL not building on Debian 10

### ISSUE THREAD

**Issue by sharkwouter** [pspdev/psplibraries#53]
When building the latest toolchain on Debian 10, OpenAL fails to build for me. Here is the log: https://gist.github.com/sharkwouter/f39f9e9891f95ed5855b302d5831df75

**Comment by carstene1ns** [comment]
Some pthread types are missing, has `pthreads-emb` been installed before?

**Comment by sharkwouter** [comment]
Yeah, it is odd. pthreads-emb installed fine. The script also works fine in the Ubuntu based docker container.

**Comment by sharkwouter** [comment]
No idea why, but I no longer see this issue
